export { default as BoDashboard } from './BoDashboard/BoDashboard'
export { default as ManagerScreen } from './ManagerScreen/ManagerScreen'
export { default as Login } from './Login/Login'
export { default as FeedbackDashboard } from './FeedbackDashbord/FeedbackDashboard'
export { default as Feedback } from './Feedback/Feedback'
export { default as UserFeedbackView } from './UserFeedbackView/UserFeedbackView'
export { default as FaqPage } from './FaQ/FaqPage'
